# Järeldused

Kõikidest soojusõpetuse, mehaanika ja keemia laboriraportitest on käesolev kõige mahukam nii sisu kui selle loomiseks kasutatud aja poolest. Tegelesin sellega umbes kuu aega. Tehnilised aspektid, kuidas raporti teatud komponente vormistada, ei võtnud nii palju aega kui psühhomeetria õppimine. Juhend on selleks liiga pealiskaudne. Juhendis olevad valemid lähtuvad tihedustest, mida ei paista mujal maailmas kasutatavat, vaid pigem nende pöördväärtust eriruumala ja rõhke. Samuti ei näidata juhendis absoluutse niiskuse valemi \@ref(eq:a) tuletamist, mistõttu ma otsisin selle ise välja. Esmalt leidsin 1933. aasta kirjutise valemi teosest [@Whipple_1933], mis tugines mitte tihedustele, vaid rõhkudele kasutades psühhomeetrilise konstandina kahe arvu suhet, mille kohta arvasin, et need on arvutuslikult välja selgitatud. Hiljem leidsin teravilja kasvatajate juhendi [@inbook], milles selgitatakse ka, kust on pärit need kaks arvu. Ühtlasi lugesin läbi Ameerika kliimaseadmete kogukonna käsiraamatu [@American_Society_of_Heating_Refrigerating_and_Air-Conditioning_Engineers2017-im] vastava osa ning vaatasin juurde Mitchell Pauluse selgitavad ja üksikasjalikud videod saamaks aru valemite tuletuskäikudest, mida nimetatud kirjalikus käsiraamatus ainult põgusalt käsitleti. Mitchell vastas ka minu küsimustele. tema võttis erisoojuste ja aurustumissoojuse aluseks vee sulamistemperatuuri, kuid Toidu- ja Põllumajanduse Liidu teoses [@inbook] nagu ka sellele tuginevas tarkvaras [@a2022_cranmeto] kasutati teistsuguseid väärtusi, mis peamiselt lähtusid n-ö toatemperatuurist ehk sellisest temperatuurist, millega enamjaolt õhuniiskust mõõdetakse psühhomeetriga. Miks on lähtutud selle temperatuuri kohastest näitajatest, selle kohta saatsin järelepärimise tarkvara autorile, kes praeguse lause kirjutamise hetkeks mulle vastanud pole - sain vaid vastuse, et ta olevat kuni augusti kaheksanda päevani eemal. Mitchelli videojuhiseid vaatasin lausa mitu korda, et kõigest aru saada. mulle oli segane nt, miks ta kasutas suhtelise niiskuse valemis \@ref(eq:relative-humidity-as-ratio-of-pressure) samaväärselt masside ja massivoogude suhet, kuni mõistsin, et ajavahemik on sama, mistõttu tühistub. tema meetodid on enamasti käsitletud *psychrolib*i tarkvaras [@psychrolibsrcrr], mille lähtekood on avalik ja seetõttu ma sain seda kasutada nii paremaks mõistmiseks kui võrdlusandmete tekitamiseks.

Psühromeetrite kasutamine oli lihtsam kui käsitsi kastepunkti määramine, mille puhul tuli võrdlemisi kaua tuimalt oodata, et tekiksid tilgad.

Huvitav asjaolu on, et mõlemad psühhomeetrid ja *Pasco* limasensor tuvastasid kõik erineva kuiva õhu temperatuuri, mida võis samaks lugeda, üksnes sajalisteni ümardades. Ka märja kolvi termomeetri temperatuurid olid erinevad ning kõige suurem erinevus kuiva ja märja kolvi temperatuuril oli *Pasco* limajaamaga. Ka kastepunktis olid erinevused. *Pasco* ilmajaama puhul ei ole mulle teada, milliste reeglite järgi toimub arvutamine, kuna lähtekood ei ole avalik. Tuvastasin ainult, et *Pasco* ilmajaama psühhomeetria osa käsitletakse Assmanni koefitsiendiga. Samuti ei kasutata *Pasco* sensoris vett, et kolv märjaks teha - seega saadakse lähteandmeid teistmoodi.

Kasutasin kokku 17 meetodit suhtelise õhuniiskuse määramiseks. Kõige ebatäpsemalt saab selle välja lugeda graafikult \@ref(fig:psychrometric-diagram), milles on õhuniiskuse aste 0.1. Lähtuvalt sellest täpsuse astmest, mahtusid kõikide kolme seadmega mõõdetud ja arvutatud õhuniiskused sobilikku vahemikku olles omavahel siiski erinevad, kuna õhutemperatuur oli erinev.

Kasutasin kokku 13 meetodit kastepunkti määramiseks. Graafikul \@ref(fig:psychrometric-diagram) oli kastepunkti täpsusaste $\qty{1}{\kelvin}$. Kui lähtuda graafiku täpsusastmest, siis kastepunktide väärtused olid ebaühtlasemad võrreldes suhtelise õhuniiskuse väärtustega.

Juhendis päritakse, millisel temperatuuril on absoluutse niiskuse väärtus arvuliselt võrdne veeauru tihedusega õhus. Mõistan seda küsimust kui et millisel temperatuuril on veeauru tegelik osarõhk võrdne veeauru küllastusrõhuga. Veeauru osarõhk on enamjaolt ühesugune. Mis muutub, on küllastusrõhk, ja seda vastavalt temperatuurile. Kui veeauru osarõhk on sama mis küllastusrõhk, siis õhku enam veeauru ei mahu ja seega on saavutatud temperatuur, millest märja kolvi termomeeter enam vähem ei näita ehk märja kolvi lõplik temperatuur.

Juhendis päritakse ka erinevust absoluutse ja suhtelise niiskuse vahel. Absoluutne niiskus on veeauru tihedus õhus [@American_Society_of_Heating_Refrigerating_and_Air-Conditioning_Engineers2017-im, p. 21]. Suhteline niiskus näitab, kui suur osa küllastumisest on saavutatud. Absoluutse niiskuse määrame massiühikus ruumala ühiku kohta ehk kasutades absoluutseid väärtusi. Suhtelise niiskuse puhul on tegemist suhtega ehk kasutatakse suhtelist väärtust.

Samuti soovitakse teada, mille poolest erineb relatiivne niiskus niiskuse puudujäägist. Relatiivne niiskus näitab, kui suur osa küllastumisest on saavutatud. Niiskuse puudujääk näitab, kui palju on veel puudu küllastumisest.

Kui kuiv-kolvi ja märg-kolvi termomeetri näidu lugemisviga on $\qty{0.2}{\kelvin}$ ja kasutada psühromeetri tabelit \@ref(tab:rh), siis sõltub vea suurus ainult kuiv-kolvi termomeetri näidust.

Suvel on relatiivne niiskus väiksem kui talvel, sest suvel on tavaliselt õhutemperatuur suurem, mistõttu mahutab õhk rohkem veeauru ning veeauru tegeliku osarõhu ja küllastusrõhu vaheline erinevus on suurem. Talvel on õhutemperatuur väiksem ja küllastusrõhk on ka väiksem, mistõttu teekond tegelikust veeauru osarõhust küllastusrõhuni on väiksem, mis tähendab suuremat suhtelist niiskust.
