# Teooria

Kui õhk oleks täiesti kuiv, siis see tähendaks, et selles puuduks veeaur. Kui õhk on täiesti märk, siis tähendab, et see on veeaurust nii küllastunud, et õhku või sellega kokkupuutes olevale õhust jahedamale pinnale tekivad tilgad. Absoluutne õhuniiskus tähendab, kui palju absoluutarvuliselt on õhus veeauru. Suhteline õhuniiskus tähendab, kui palju on õhus veeauru suhteliselt. Eelnevas kuiva õhu näites on õhus veeauru 0, täiesti märjas ehk veeaurust küllastunud õhus 1.

Joonisel \@ref(fig:relative-humidity) on näidatud, kuidas suhteline õhuniiskus ja õhutemperatuur on omavahel seotud. Kuum õhk mahutab rohkem veeauru kui jahe õhk, sest selles on õhu osakesed üksteisest kaugemal ja rohkem on ruumi veeauru osakeste jaoks nende vahel. Seega, kui veeauru kogus õhus on muutumatu, on veeauru kuumas õhus suhteliselt vähem kui jahedas õhus. Kui veeauru on õhus 1, siis on õhk veeaurust küllastunud ja sellesse rohkem veeauru ei mahu, mis tähendab, et edasine õhu jahtumine toob kaasa veeauru kondenseerumise. Olek, milles õhk on veeaurust küllastunud, on seega kastepunkt.

(ref:relative-humidity) @news_september

```{r label = "relative-humidity", fig.cap = "Suhtelise õhuniiskuse ja õhu temperatuuri seos ((ref:relative-humidity)).", fig.margin = TRUE}
include_svg("relative-humidity.webp")
```

Õhuniiskust saab mõõta psühromeetriga. Viimases on kaks termomeetrit: üks kuiva, teine niiske õhu jaoks. Kuiva õhu termomeetri näitu ei manipuleerita. Küll aga tehakse niiskeks teise termomeetri sensor, misjärel hakkab selle termomeetri näit vähenema, sest see niiskus aurub ja aurumisel võetakse ümbritsevast keskkonnast soojusenergiat, mistõttu ümbritsev keskkond jahtub. See jahtumine toimub siiski ainult selle termomeetri sensori ümber ja ei mõjuta teise termomeetri sensori ümbrust. Niiske termomeetri näit langeb, kuni see enam langeda ei saa, st on saavutatud olek, milles edasine aurumine on võimatu, sest õhk ei võta rohkem auru vastu - on jõutud küllastuspunktini.

Õhutemperatuur saab langeda veel kastepunktini, mis on selline temperatuur, mille juures hakkab veeaur õhust pinnale, mille temperatuur on kastepunktist väiksem, kondenseeruma.

Kastepunkti saab otse mõõta võttes nt mingi keraja metalse või klaaspinnaga kausi ja täites selle kausi ainega, mille temperatuur on sama mis õhutemperatuur. Seejärel tuleb kausis oleva aine temperatuuri alandada ja kui kausi välispinnale tekivad tilgad, ongi saavutatud kastepunkt.

Selleks, et arvutada suhtelist õhuniiskust, on vaja teada kas rõhke või masse. Kumbagi on keeruline otse mõõta. Lihtne on mõõta temperatuuri ja temperatuuride järgi saab arvutada rõhud. Arvutamiseeskiri võiks olla selline:

1. küllastusrõhu arvutamine õhutemperatuuri (kuiv termomeetri kolv) järgi kasutades valemit \@ref(eq:saturation-pressure-over-liquid-h2o) või \@ref(eq:saturation-pressure-in-inbook),

2. tegeliku rõhu arvutamine kuiva ja märja kolviga termomeetri temperatuuride, atmosfäärirõhu ja psühromeetri tüübi järgi kasutades valemit \@ref(eq:actual-vapor-pressure),

3. suhtelise niiskuse arvutamine kasutades tegelikku ja küllastusrõhku, nagu esitatud valemis \@ref(eq:relative-humidity-as-ratio-of-pressure).